#ifndef TYPE_HELPERS_H
#define TYPE_HELPERS_H

#define MAKE_TYPE_ARG(STRUCT_NAME, STRUCT_DEFINITION, OPTIONAL_CSTYLE_VARIABLE) \
struct STRUCT_NAME { \
    STRUCT_DEFINITION \
} OPTIONAL_CSTYLE_VARIABLE; \
typedef const STRUCT_NAME& STRUCT_NAME##Arg;

#define FARG(TYPE, NAME) const TYPE& NAME

#endif // TYPE_HELPERS_H
