project(Nostalgia)

set(NOSTALGIA_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia")
set(EDITOR_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/Editor")

set(EDITOR_SRC_FILES
    ${EDITOR_ROOT}/things/player.cpp
    ${EDITOR_ROOT}/things/test_animated_sprite.cpp
    ${EDITOR_ROOT}/app/nostalgia_goggles.cpp
    ${EDITOR_ROOT}/system/dedicated_main.cpp
    ${EDITOR_ROOT}/tools/stopwatch_log.cpp
    ${EDITOR_ROOT}/gui/imgui_implementor.cpp
    ${EDITOR_ROOT}/gui/imgui_debugger.cpp
    ${EDITOR_ROOT}/gui/imgui_editor.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_impl_opengl3.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_widgets.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_stdlib.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_tables.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_impl_glfw.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_demo.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_freetype.cpp
    ${EDITOR_ROOT}/thirdparty/DearImGui/imgui_draw.cpp)

set(NOSTALGIA_SRC_FILES
    ${NOSTALGIA_ROOT}/backends/opengl/gl_graphics_context.cpp
    ${NOSTALGIA_ROOT}/backends/opengl/gl_mesh_buffers.cpp
    ${NOSTALGIA_ROOT}/backends/opengl/gl_vertex_array.cpp
    ${NOSTALGIA_ROOT}/backends/opengl/gl_texture_buffer.cpp
    ${NOSTALGIA_ROOT}/backends/opengl/gl_shader.cpp
    ${NOSTALGIA_ROOT}/backends/opengl/gl_renderer_api.cpp
    ${NOSTALGIA_ROOT}/backends/opengl/gl_frame_buffer.cpp
    ${NOSTALGIA_ROOT}/backends/glfw/glfw_window.cpp
    ${NOSTALGIA_ROOT}/managers/event_manager.cpp
    ${NOSTALGIA_ROOT}/managers/physics_manager.cpp
    ${NOSTALGIA_ROOT}/managers/input_manager.cpp
    ${NOSTALGIA_ROOT}/managers/render_manager.cpp
    ${NOSTALGIA_ROOT}/managers/theatre_manager.cpp
    ${NOSTALGIA_ROOT}/managers/manager.cpp
    ${NOSTALGIA_ROOT}/managers/ui_manager.cpp
    ${NOSTALGIA_ROOT}/settings/world.cpp
    ${NOSTALGIA_ROOT}/core/uid.cpp
    ${NOSTALGIA_ROOT}/core/time.cpp
    ${NOSTALGIA_ROOT}/core/message_labels.cpp
    ${NOSTALGIA_ROOT}/core/bitmask.cpp
    ${NOSTALGIA_ROOT}/core/ansi_sequence.cpp
    ${NOSTALGIA_ROOT}/core/log.cpp
    ${NOSTALGIA_ROOT}/core/id.cpp
    ${NOSTALGIA_ROOT}/application/application.cpp
    ${NOSTALGIA_ROOT}/application/window.cpp
    ${NOSTALGIA_ROOT}/events/action.cpp
    ${NOSTALGIA_ROOT}/events/event_queue.cpp
    ${NOSTALGIA_ROOT}/events/event.cpp
    ${NOSTALGIA_ROOT}/ui/implementor.cpp
    ${NOSTALGIA_ROOT}/ui/solution.cpp
    ${NOSTALGIA_ROOT}/theatre/theatre.cpp
    ${NOSTALGIA_ROOT}/things/resource_database.cpp
    ${NOSTALGIA_ROOT}/things/thing.cpp
    ${NOSTALGIA_ROOT}/things/resources/image_texture.cpp
    ${NOSTALGIA_ROOT}/things/resources/image.cpp
    ${NOSTALGIA_ROOT}/things/resources/material.cpp
    ${NOSTALGIA_ROOT}/things/resources/font.cpp
    ${NOSTALGIA_ROOT}/things/resources/mesh.cpp
    ${NOSTALGIA_ROOT}/things/resources/cubemap.cpp
    ${NOSTALGIA_ROOT}/things/resources/viewport_texture.cpp
    ${NOSTALGIA_ROOT}/things/resources/texture.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/light_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/visual_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/mesh_instance_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/collider_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/actor_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/camera_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/sprite_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/nostalgia_player_3d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/camera_2d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/actor_2d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/sprite_2d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/text_2d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/visual_2d.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/viewport.cpp
    ${NOSTALGIA_ROOT}/things/thinkers/thinker.cpp
    ${NOSTALGIA_ROOT}/things/thing_type.cpp
    ${NOSTALGIA_ROOT}/things/thing_factory.cpp
    ${NOSTALGIA_ROOT}/things/thing_data.cpp
    ${NOSTALGIA_ROOT}/things/thing_variable.cpp
    ${NOSTALGIA_ROOT}/theatre/parser/parser.cpp
    ${NOSTALGIA_ROOT}/theatre/parser/lexer.cpp
    ${NOSTALGIA_ROOT}/theatre/call_sheet.cpp
    ${NOSTALGIA_ROOT}/theatre/theatre_file.cpp
    ${NOSTALGIA_ROOT}/theatre/tree.cpp
    ${NOSTALGIA_ROOT}/filesystem/file_data.cpp
    ${NOSTALGIA_ROOT}/filesystem/filesystem.cpp
    ${NOSTALGIA_ROOT}/physics/engine.cpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/glm.cpp
    ${NOSTALGIA_ROOT}/thirdparty/glad/glad.c
    ${NOSTALGIA_ROOT}/rendering/texture_buffer.cpp
    ${NOSTALGIA_ROOT}/rendering/shader.cpp
    ${NOSTALGIA_ROOT}/rendering/renderer_api.cpp
    ${NOSTALGIA_ROOT}/rendering/graphics_context.cpp
    ${NOSTALGIA_ROOT}/rendering/vertex_array.cpp
    ${NOSTALGIA_ROOT}/rendering/mesh_buffers.cpp
    ${NOSTALGIA_ROOT}/rendering/frame_buffer.cpp
    ${NOSTALGIA_ROOT}/console/console.cpp
    ${NOSTALGIA_ROOT}/math/conversion.cpp)

set(NOSTALGIA_HEADERS
    ${NOSTALGIA_ROOT}/managers/ui_manager.hpp
    ${NOSTALGIA_ROOT}/managers/input_manager.hpp
    ${NOSTALGIA_ROOT}/managers/theatre_manager.hpp
    ${NOSTALGIA_ROOT}/managers/manager.hpp
    ${NOSTALGIA_ROOT}/managers/render_manager.hpp
    ${NOSTALGIA_ROOT}/managers/physics_manager.hpp
    ${NOSTALGIA_ROOT}/managers/event_manager.hpp
    ${NOSTALGIA_ROOT}/settings/player.hpp
    ${NOSTALGIA_ROOT}/settings/engine.hpp
    ${NOSTALGIA_ROOT}/settings/graphics.hpp
    ${NOSTALGIA_ROOT}/settings/world.hpp
    ${NOSTALGIA_ROOT}/core/error.hpp
    ${NOSTALGIA_ROOT}/core/vector.hpp
    ${NOSTALGIA_ROOT}/core/smart_pointers.hpp
    ${NOSTALGIA_ROOT}/core/uid.hpp
    ${NOSTALGIA_ROOT}/core/ansi_sequence.hpp
    ${NOSTALGIA_ROOT}/core/id.hpp
    ${NOSTALGIA_ROOT}/core/ansi_codes.hpp
    ${NOSTALGIA_ROOT}/core/mutex.hpp
    ${NOSTALGIA_ROOT}/core/message_labels.hpp
    ${NOSTALGIA_ROOT}/core/enum_registry.hpp
    ${NOSTALGIA_ROOT}/core/farg.hpp
    ${NOSTALGIA_ROOT}/core/bitmask.hpp
    ${NOSTALGIA_ROOT}/core/concepts.hpp
    ${NOSTALGIA_ROOT}/core/types.hpp
    ${NOSTALGIA_ROOT}/core/macros.hpp
    ${NOSTALGIA_ROOT}/core/constexpr_string_hash.hpp
    ${NOSTALGIA_ROOT}/core/log.hpp
    ${NOSTALGIA_ROOT}/core/time.hpp
    ${NOSTALGIA_ROOT}/application/window.hpp
    ${NOSTALGIA_ROOT}/application/monitor.hpp
    ${NOSTALGIA_ROOT}/application/application.hpp
    ${NOSTALGIA_ROOT}/events/bindings.hpp
    ${NOSTALGIA_ROOT}/events/action.hpp
    ${NOSTALGIA_ROOT}/events/event_queue.hpp
    ${NOSTALGIA_ROOT}/events/event.hpp
    ${NOSTALGIA_ROOT}/ui/solution.hpp
    ${NOSTALGIA_ROOT}/ui/implementor.hpp
    ${NOSTALGIA_ROOT}/theatre/theatre.hpp
    ${NOSTALGIA_ROOT}/things/resource_database.hpp
    ${NOSTALGIA_ROOT}/things/resources/image_texture.hpp
    ${NOSTALGIA_ROOT}/things/resources/image.hpp
    ${NOSTALGIA_ROOT}/things/resources/texture.hpp
    ${NOSTALGIA_ROOT}/things/resources/cubemap.hpp
    ${NOSTALGIA_ROOT}/things/resources/viewport_texture.hpp
    ${NOSTALGIA_ROOT}/things/resources/font.hpp
    ${NOSTALGIA_ROOT}/things/resources/resource.hpp
    ${NOSTALGIA_ROOT}/things/resources/mesh.hpp
    ${NOSTALGIA_ROOT}/things/resources/material.hpp
    ${NOSTALGIA_ROOT}/things/thing.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/nostalgia_player_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/sprite_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/collider_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/actor_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/visual_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/mesh_instance_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/camera_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/3d/light_3d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/viewport.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/visual_2d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/sprite_2d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/actor_2d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/text_2d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/2d/camera_2d.hpp
    ${NOSTALGIA_ROOT}/things/thinkers/thinker.hpp
    ${NOSTALGIA_ROOT}/things/thing_type.hpp
    ${NOSTALGIA_ROOT}/things/thing_factory.hpp
    ${NOSTALGIA_ROOT}/theatre/theatre_file.hpp
    ${NOSTALGIA_ROOT}/theatre/tree.hpp
    ${NOSTALGIA_ROOT}/things/thing_data.hpp
    ${NOSTALGIA_ROOT}/theatre/call_sheet.hpp
    ${NOSTALGIA_ROOT}/theatre/parser/number_parser.hpp
    ${NOSTALGIA_ROOT}/filesystem/file_data.hpp
    ${NOSTALGIA_ROOT}/filesystem/filesystem.hpp
    ${NOSTALGIA_ROOT}/physics/engine.hpp
    ${NOSTALGIA_ROOT}/rendering/graphics_context.hpp
    ${NOSTALGIA_ROOT}/rendering/renderer_api.hpp
    ${NOSTALGIA_ROOT}/rendering/common.hpp
    ${NOSTALGIA_ROOT}/rendering/debugging.hpp
    ${NOSTALGIA_ROOT}/rendering/vertex_array.hpp
    ${NOSTALGIA_ROOT}/rendering/environment.hpp
    ${NOSTALGIA_ROOT}/rendering/vertex.hpp
    ${NOSTALGIA_ROOT}/rendering/frame_buffer.hpp
    ${NOSTALGIA_ROOT}/rendering/mesh_buffers.hpp
    ${NOSTALGIA_ROOT}/rendering/shader.hpp
    ${NOSTALGIA_ROOT}/rendering/texture_buffer.hpp
    ${NOSTALGIA_ROOT}/console/console.hpp
    ${NOSTALGIA_ROOT}/common/colors.hpp
    ${NOSTALGIA_ROOT}/common/status_map.hpp
    ${NOSTALGIA_ROOT}/common/string_compare.hpp
    ${NOSTALGIA_ROOT}/components/game_loop.hpp
    ${NOSTALGIA_ROOT}/components/event_handling.hpp
    ${NOSTALGIA_ROOT}/fwd/ui.hpp
    ${NOSTALGIA_ROOT}/fwd/theatre.hpp
    ${NOSTALGIA_ROOT}/fwd/rendering.hpp
    ${NOSTALGIA_ROOT}/fwd/things.hpp
    ${NOSTALGIA_ROOT}/fwd/managers.hpp
    ${NOSTALGIA_ROOT}/fwd/core.hpp
    ${NOSTALGIA_ROOT}/fwd/events.hpp
    ${NOSTALGIA_ROOT}/fwd/event_types.hpp
    ${NOSTALGIA_ROOT}/fwd/application.hpp
    ${NOSTALGIA_ROOT}/Nostalgia.hpp
    ${NOSTALGIA_ROOT}/math/transform.hpp
    ${NOSTALGIA_ROOT}/math/glm_format.hpp
    ${NOSTALGIA_ROOT}/math/conversion.hpp
    ${NOSTALGIA_ROOT}/math/glm_concepts.hpp)

set(NOSTALGIA_GLM_HEADERS
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int3x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float2x3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint3x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_clip_space.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double3x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_reciprocal.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int3x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_packing.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_common.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_exponential.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint4x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float3x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float3x3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_trigonometric.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_ulp.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint2x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float3x2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float4x4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double1_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float4x3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int1.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double2x3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int2x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_projection.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint4x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint2x4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint2x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_common.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int4x4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float4x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float2x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_double_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double4x2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float2x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint1_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double2x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_integer.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_reciprocal.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double4x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int4x2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float4x2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_integer.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_common.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int4x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int2x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int3x4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int4x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double3x3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_double.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint3x4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_relational.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int4x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint3x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_int_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double2x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int3x3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_ulp.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double3x4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float4x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double4x4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int2x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float2x4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int2x3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float3x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double3x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double4x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double3x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float1_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool1.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double4x3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint4x3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double4x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_relational.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float1.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int3x2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint1.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_packing.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint4x2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool1_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint4x4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_uint_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int2x2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_float.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float4x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_constants.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int2x4_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_common.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_transform.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double2x4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float2x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int1_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint2x2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_geometric.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_float_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint3x2_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float2x2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float3x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double2x2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_double1.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_transform.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_float3x4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int3x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double2x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_bool3_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint3x3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_double3x2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint4x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_int3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint2x3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint2x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_relational.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/_matrix_vectorize.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_uint3x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float4_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_int4x3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_relational.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_uint3_sized.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_integer.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_float2_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat2x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/geometric.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat4x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat2x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/vec2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/transform2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/vec_swizzle.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/raw_data.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/color_encoding.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/euler_angles.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_interpolation.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/polar_coordinates.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_factorisation.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_major_storage.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/vector_query.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/gradient_paint.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/texture.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/component_wise.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/fast_exponential.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/fast_square_root.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/norm.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/vector_angle.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_transform_2d.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/dual_quaternion.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/color_space.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/hash.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/string_cast.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/closest_point.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/normalize_dot.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/mixed_product.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/common.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/quaternion.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/pca.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/std_based_type.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/associated_min_max.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/perpendicular.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/color_space_YCoCg.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/transform.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/projection.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/number_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/extend.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/io.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/integer.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/exterior_product.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/rotate_normalized_axis.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/rotate_vector.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/type_trait.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/type_aligned.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/easing.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/handed_coordinate_space.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_decompose.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/wrap.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/functions.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/fast_trigonometry.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/intersect.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/compatibility.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/normal.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_cross_product.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_operation.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/orthonormalize.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/optimum_pow.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/bit.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/range.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/log_base.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/scalar_relational.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/scalar_multiplication.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/extended_min_max.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/spline.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_query.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/vec4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat2x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/matrix.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/bitfield.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/random.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/vec1.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/round.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/color_space.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/quaternion.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/matrix_integer.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/constants.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/type_precision.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/integer.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/type_aligned.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/type_ptr.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/packing.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/matrix_access.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/reciprocal.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/matrix_transform.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/matrix_inverse.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/ulp.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/noise.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/epsilon.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat3x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/common.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat3x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat4x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/exponential.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat3x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/integer.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/trigonometric.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/platform.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/matrix.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/exponential.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/packing.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/neon.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/geometric.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/integer.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/common.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/simd/vector_relational.h
    ${NOSTALGIA_ROOT}/thirdparty/glm/glm.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/packing.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/_vectorize.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat2x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat4x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/compute_common.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/_swizzle.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat3x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/qualifier.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_quat.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/_fixes.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_half.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat4x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/compute_vector_relational.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_float.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/_features.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat2x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat2x2.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/compute_vector_decl.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat3x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat3x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/_noise.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat4x3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec1.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/setup.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/_swizzle_func.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/trigonometric.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/fwd.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/mat4x4.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/vector_relational.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/vec3.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext.hpp
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_transform.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_exponential.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_reciprocal.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_integer.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_relational.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_integer.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_constants.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_ulp.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_clip_space.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_relational.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_reciprocal.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_transform.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_packing.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_relational.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_projection.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_relational.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_common.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_ulp.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_geometric.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_common.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/vector_common.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/scalar_packing.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_common_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_common.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/quaternion_trigonometric.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/ext/matrix_integer.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/exterior_product.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/normalize_dot.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_transform_2d.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/spline.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/euler_angles.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/string_cast.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/fast_square_root.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/pca.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/perpendicular.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_operation.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/intersect.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/vector_angle.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/compatibility.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/bit.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/rotate_vector.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/vector_query.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/fast_exponential.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/color_space.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_cross_product.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/orthonormalize.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/easing.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/scalar_relational.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/integer.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_factorisation.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_interpolation.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/rotate_normalized_axis.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/quaternion.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/wrap.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/functions.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/hash.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/norm.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/optimum_pow.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/dual_quaternion.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/polar_coordinates.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/float_notmalize.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/mixed_product.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/component_wise.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/gradient_paint.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_query.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/type_trait.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/extend.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/io.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/associated_min_max.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/log_base.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/color_encoding.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/normal.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/closest_point.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/common.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/transform2.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/extended_min_max.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/handed_coordinate_space.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/transform.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/color_space_YCoCg.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/fast_trigonometry.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/type_aligned.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/raw_data.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_decompose.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/texture.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/matrix_major_storage.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/projection.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtx/std_based_type.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/quaternion_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/matrix_transform.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/type_precision.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/color_space.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/random.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/integer.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/quaternion.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/round.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/constants.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/packing.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/type_ptr.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/matrix_inverse.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/bitfield.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/ulp.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/noise.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/epsilon.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/gtc/matrix_access.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_packing_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_common_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat4x3.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_integer_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec1.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_common.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec4_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_trigonometric.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_exponential_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_trigonometric_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_geometric_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat3x3.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat4x2.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_matrix_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_matrix.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat4x4.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat3x4.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat2x2.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_geometric.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_packing.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_quat.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat4x4_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_vector_relational_simd.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat2x3.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_exponential.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec2.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat2x4.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec3.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_vector_relational.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_mat3x2.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_vec4.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/func_integer.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_half.inl
    ${NOSTALGIA_ROOT}/thirdparty/glm/detail/type_quat_simd.inl)

set(NOSTALGIA_JOLT_HEADERS
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/StateRecorder.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/FixedConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/DistanceConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/SixDOFConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/RackAndPinionConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/SpringSettings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/TwoBodyConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintManager.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/PathConstraintPath.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/HingeConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/PathConstraintPathHermite.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/PulleyConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/PointConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/SwingTwistConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/PathConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/SliderConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ContactConstraintManager.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/CalculateSolverSteps.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/AxisConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/IndependentAxisConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/RackAndPinionConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/RotationQuatConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/SpringPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/GearConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/RotationEulerConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/PointConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/DualAxisConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/AngleConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/HingeRotationConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConstraintPart/SwingTwistConstraintPart.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/MotorSettings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/ConeConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/GearConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Constraints/Constraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Ragdoll/Ragdoll.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/StateRecorderImpl.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/EPhysicsUpdateError.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/PhysicsUpdateContext.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/IslandBuilder.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/LargeIslandSplitter.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodyVertex.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodyUpdateContext.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodyShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodySharedSettings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodyContactListener.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodyCreationSettings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodyManifold.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/SoftBody/SoftBodyMotionProperties.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollideShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/SimShapeFilterWrapper.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollideConvexVsTriangles.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ActiveEdges.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ManifoldBetweenTwoFaces.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/ObjectVsBroadPhaseLayerFilterTable.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/BroadPhaseQuery.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/BroadPhaseQuadTree.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/BroadPhase.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/QuadTree.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/BroadPhaseBruteForce.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/BroadPhaseLayerInterfaceMask.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/BroadPhaseLayer.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/BroadPhaseLayerInterfaceTable.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BroadPhase/ObjectVsBroadPhaseLayerFilterMask.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/AABoxCast.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollectFacesMode.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/PhysicsMaterial.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/TaperedCapsuleShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/SphereShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/StaticCompoundShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/PolyhedronSubmergedVolumeCalculator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/CompoundShapeVisitors.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/SubShapeIDPair.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/ConvexHullShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/MutableCompoundShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/ConvexShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/HeightFieldShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/GetTrianglesContext.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/SubShapeID.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/TriangleShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/MeshShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/RotatedTranslatedShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/ScaleHelpers.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/DecoratedShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/CompoundShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/BoxShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/PlaneShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/TaperedCylinderShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/EmptyShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/OffsetCenterOfMassShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/ScaledShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/Shape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/CylinderShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/Shape/CapsuleShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CastResult.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/SimShapeFilter.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/EstimateCollisionResponse.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CastConvexVsTriangles.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ObjectLayerPairFilterTable.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/RayCast.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollideSoftBodyVertexIterator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/NarrowPhaseQuery.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/BackFaceMode.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ShapeCast.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollideSoftBodyVerticesVsTriangles.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/NarrowPhaseStats.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ShapeFilter.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollisionCollectorImpl.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/PhysicsMaterialSimple.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollisionGroup.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollideSphereVsTriangles.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/GroupFilterTable.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/InternalEdgeRemovingCollector.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CastSphereVsTriangles.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ContactListener.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollideShapeVsShapePerLeaf.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ActiveEdgeMode.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ObjectLayerPairFilterMask.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/GroupFilter.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollisionDispatch.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/ObjectLayer.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/TransformedShape.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollidePointResult.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/CollisionCollector.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Collision/SortReverseAndStore.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Character/CharacterBase.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Character/CharacterID.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Character/Character.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Character/CharacterVirtual.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyLockMulti.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/AllowedDOFs.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyAccess.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyManager.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyPair.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyActivationListener.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyID.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyType.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/MotionType.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/Body.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/MotionProperties.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyLock.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyFilter.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyInterface.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/MassProperties.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/MotionQuality.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyLockInterface.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/BodyCreationSettings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/PhysicsSettings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/PhysicsSystem.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/PhysicsLock.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/PhysicsScene.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/DeterminismLog.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/PhysicsStepListener.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/TrackedVehicleController.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleTrack.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleTransmission.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/MotorcycleController.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleAntiRollBar.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleConstraint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleDifferential.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/WheeledVehicleController.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleCollisionTester.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleEngine.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/VehicleController.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Vehicle/Wheel.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Hair/HairShaders.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Hair/HairSettings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Hair/Hair.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/EActivation.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Quat.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Float4.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/EigenValueSymmetric.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Vector.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Float3.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/DMat44.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/DynMatrix.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Mat44.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/FindRoot.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Vec4.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/MathTypes.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/HalfFloat.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Double3.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Math.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/DVec3.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Real.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/UVec4.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Float2.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/GaussianElimination.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Trigonometry.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/BVec16.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Matrix.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Vec3.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Swizzle.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/Triangle.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/ClipPoly.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/IndexedTriangle.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/ConvexHullBuilder.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/GJKClosestPoint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/RayCapsule.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/Ellipse.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/ClosestPoint.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/EPAPenetrationDepth.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/AABox.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/EPAConvexHullBuilder.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/Plane.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/RayCylinder.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/RayTriangle.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/RayAABox.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/MortonCode.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/OrientedBox.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/ConvexSupport.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/Indexify.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/ConvexHullBuilder2D.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/RaySphere.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/Sphere.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Geometry/AABox4.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/AABBTree/AABBTreeBuilder.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/AABBTree/AABBTreeToBuffer.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/AABBTree/NodeCodec/NodeCodecQuadTreeHalfFloat.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/AABBTree/TriangleCodec/TriangleCodecIndexed8BitPackSOA4Flags.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Jolt.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ConfigurationString.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Renderer/DebugRenderer.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Renderer/DebugRendererSimple.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Renderer/DebugRendererRecorder.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Renderer/DebugRendererPlayback.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStreamBinaryOut.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/SerializableAttributeTyped.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStreamIn.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/SerializableAttribute.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/TypeDeclarations.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStreamBinaryIn.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStreamTypes.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStream.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStreamTextIn.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStreamTextOut.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/SerializableAttributeEnum.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/GetPrimitiveTypeOfType.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/SerializableObject.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/ObjectStream/ObjectStreamOut.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Skeleton/SkeletalAnimation.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Skeleton/Skeleton.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Skeleton/SkeletonPose.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Skeleton/SkeletonMapper.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/RegisterTypes.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/ComputeShaderVK.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/BufferVK.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/ComputeBufferVK.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/ComputeSystemVKImpl.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/ComputeQueueVK.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/IncludeVK.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/ComputeSystemVK.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/VK/ComputeSystemVKWithAllocator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/ComputeBuffer.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/ComputeQueue.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/ShaderWrapper.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/WrapShaderEnd.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/WrapShaderBindings.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/ComputeQueueCPU.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/HLSLToCPP.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/ComputeSystemCPU.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/ComputeShaderCPU.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/ComputeBufferCPU.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/CPU/WrapShaderBegin.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/ComputeShader.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Compute/ComputeSystem.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/StringTools.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/BinaryHeap.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/MutexArray.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/QuickSort.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Mutex.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/JobSystem.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/RTTI.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/StridedPtr.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Profiler.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/UnorderedMapFwd.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/JobSystemSingleThreaded.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/UnorderedSet.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/LockFreeHashMap.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/FixedSizeFreeList.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/JobSystemWithBarrier.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/STLAlignedAllocator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/ScopeExit.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/IssueReporting.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Core.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/StreamOut.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/HashTable.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/StaticArray.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/FPControlWord.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Result.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/ARMNeon.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/TickCounter.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/UnorderedSetFwd.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/StreamWrapper.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/StreamUtils.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/ByteBuffer.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/IncludeWindows.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/JobSystemThreadPool.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/HashCombine.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/STLTempAllocator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/TempAllocator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/ObjectToIDMap.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/STLAllocator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/STLLocalAllocator.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Array.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/FPException.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Atomics.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Color.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Factory.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Memory.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Reference.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/StreamIn.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Semaphore.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/NonCopyable.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/UnorderedMap.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/InsertionSort.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/FPFlushDenormals.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/LinearCurve.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Shaders/HairWrapper.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/TriangleSplitter/TriangleSplitterMean.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/TriangleSplitter/TriangleSplitter.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/TriangleSplitter/TriangleSplitterBinning.h
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/Body.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Physics/Body/MotionProperties.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Mat44.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/UVec4.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/BVec16.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/DMat44.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Vec4.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Vec3.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/Quat.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Math/DVec3.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/JobSystem.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/Profiler.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/LockFreeHashMap.inl
    ${NOSTALGIA_ROOT}/thirdparty/Jolt/Core/FixedSizeFreeList.inl)
