project(Nostalgia)

# Disable most messages from other CMakeLists.txt files
set(CMAKE_REQUIRED_QUIET ON)
set(CMAKE_RULE_MESSAGES OFF)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia/thirdparty/zlib)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia/thirdparty/bzip2)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia/thirdparty/brotli)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia/thirdparty/libpng)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia/thirdparty/freetype)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia/thirdparty/glfw)
set(_build_type ${CMAKE_BUILD_TYPE})
set(CMAKE_BUILD_TYPE "ReleaseASAN")
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/Nostalgia/thirdparty/JoltPhysics/Build)
set(CMAKE_BUILD_TYPE ${_build_type})
# Re-enable messages
set(CMAKE_REQUIRED_QUIET OFF)
set(CMAKE_RULE_MESSAGES ON)
# Hide thirdparty CMake options behind the "advanced" option in cmake-gui
mark_as_advanced(CLEAR CMAKE_BUILD_TYPE)
mark_as_advanced(CLEAR BUILD_SHARED_LIBS)
mark_as_advanced(CLEAR GENERATE_DEBUG_SYMBOLS)
mark_as_advanced(FORCE CMAKE_INSTALL_PREFIX)
mark_as_advanced(FORCE X11_xcb_xkb_INCLUDE_PATH)
mark_as_advanced(FORCE WAYLAND_SCANNER_EXECUTABLE)
mark_as_advanced(FORCE BROTLI_INCLUDE_DIRS)
mark_as_advanced(FORCE ld-version-script)
mark_as_advanced(FORCE AWK)
mark_as_advanced(FORCE USE_ASSERTS)
mark_as_advanced(FORCE DOUBLE_PRECISION)
mark_as_advanced(FORCE JPH_DEBUG_SYMBOL_FORMAT)
mark_as_advanced(FORCE OVERRIDE_CXX_FLAGS)
mark_as_advanced(FORCE CROSS_PLATFORM_DETERMINISTIC)
mark_as_advanced(FORCE CROSS_COMPILE_ARM)
mark_as_advanced(FORCE INTERPROCEDURAL_OPTIMIZATION)
mark_as_advanced(FORCE FLOATING_POINT_EXCEPTIONS_ENABLED)
mark_as_advanced(FORCE CPP_EXCEPTIONS_ENABLED)
mark_as_advanced(FORCE OBJECT_LAYER_BITS)
mark_as_advanced(FORCE USE_SSE4_1)
mark_as_advanced(FORCE USE_SSE4_2)
mark_as_advanced(FORCE USE_AVX)
mark_as_advanced(FORCE USE_AVX2)
mark_as_advanced(FORCE USE_AVX512)
mark_as_advanced(FORCE USE_LZCNT)
mark_as_advanced(FORCE USE_TZCNT)
mark_as_advanced(FORCE USE_F16C)
mark_as_advanced(FORCE USE_FMADD)
mark_as_advanced(FORCE USE_WASM_SIMD)
mark_as_advanced(FORCE JPH_USE_WASM64)
mark_as_advanced(FORCE ENABLE_ALL_WARNINGS)
mark_as_advanced(FORCE ENABLE_INSTALL)
mark_as_advanced(FORCE TRACK_BROADPHASE_STATS)
mark_as_advanced(FORCE TRACK_NARROWPHASE_STATS)
mark_as_advanced(FORCE JPH_TRACK_SIMULATION_STATS)
mark_as_advanced(FORCE DEBUG_RENDERER_IN_DEBUG_AND_RELEASE)
mark_as_advanced(FORCE DEBUG_RENDERER_IN_DISTRIBUTION)
mark_as_advanced(FORCE PROFILER_IN_DEBUG_AND_RELEASE)
mark_as_advanced(FORCE PROFILER_IN_DISTRIBUTION)
mark_as_advanced(FORCE JPH_USE_EXTERNAL_PROFILE)
mark_as_advanced(FORCE DISABLE_CUSTOM_ALLOCATOR)
mark_as_advanced(FORCE USE_STD_VECTOR)
mark_as_advanced(FORCE ENABLE_OBJECT_STREAM)
