// 'frozen' maps for converting various values between different windowing libraries and Nostalgia

#include "glfw.hpp"
#include "GLFW/glfw3.h"

constexpr frozen::map<id_t, id_t, InputID::KeysCount + InputID::MouseButtonsCount>
GLFW_Backend::s_cInputIdToGlfw =
{
    { InputID::KeyZERO,  GLFW_KEY_0 },
    { InputID::KeyONE,   GLFW_KEY_1 },
    { InputID::KeyTWO,   GLFW_KEY_2 },
    { InputID::KeyTHREE, GLFW_KEY_3 },
    { InputID::KeyFOUR,  GLFW_KEY_4 },
    { InputID::KeyFIVE,  GLFW_KEY_5 },
    { InputID::KeySIX,   GLFW_KEY_6 },
    { InputID::KeySEVEN, GLFW_KEY_7 },
    { InputID::KeyEIGHT, GLFW_KEY_8 },
    { InputID::KeyNINE,  GLFW_KEY_9 },
    { InputID::KeyA, GLFW_KEY_A },
    { InputID::KeyB, GLFW_KEY_B },
    { InputID::KeyC, GLFW_KEY_C },
    { InputID::KeyD, GLFW_KEY_D },
    { InputID::KeyE, GLFW_KEY_E },
    { InputID::KeyF, GLFW_KEY_F },
    { InputID::KeyG, GLFW_KEY_G },
    { InputID::KeyH, GLFW_KEY_H },
    { InputID::KeyI, GLFW_KEY_I },
    { InputID::KeyJ, GLFW_KEY_J },
    { InputID::KeyK, GLFW_KEY_K },
    { InputID::KeyL, GLFW_KEY_L },
    { InputID::KeyM, GLFW_KEY_M },
    { InputID::KeyN, GLFW_KEY_N },
    { InputID::KeyO, GLFW_KEY_O },
    { InputID::KeyP, GLFW_KEY_P },
    { InputID::KeyQ, GLFW_KEY_Q },
    { InputID::KeyR, GLFW_KEY_R },
    { InputID::KeyS, GLFW_KEY_S },
    { InputID::KeyT, GLFW_KEY_T },
    { InputID::KeyU, GLFW_KEY_U },
    { InputID::KeyV, GLFW_KEY_V },
    { InputID::KeyW, GLFW_KEY_W },
    { InputID::KeyX, GLFW_KEY_X },
    { InputID::KeyY, GLFW_KEY_Y },
    { InputID::KeyZ, GLFW_KEY_Z },
    { InputID::KeyLEFTSHIFT,    GLFW_KEY_LEFT_SHIFT      },
    { InputID::KeyRIGHTSHIFT,   GLFW_KEY_RIGHT_SHIFT     },
    { InputID::KeyLEFTCONTROL,  GLFW_KEY_LEFT_CONTROL    },
    { InputID::KeyRIGHTCONTROL, GLFW_KEY_RIGHT_CONTROL   },
    { InputID::KeyLEFTALT,      GLFW_KEY_LEFT_ALT        },
    { InputID::KeyRIGHTALT,     GLFW_KEY_RIGHT_ALT       },
    { InputID::KeyLEFTSUPER,    GLFW_KEY_LEFT_SUPER      },
    { InputID::KeyRIGHTSUPER,   GLFW_KEY_RIGHT_SUPER     },
    { InputID::KeyENTER,        GLFW_KEY_ENTER           },
    { InputID::KeyBACKSPACE,    GLFW_KEY_BACKSPACE       },
    { InputID::KeyTAB,          GLFW_KEY_TAB             },
    { InputID::KeySPACE,        GLFW_KEY_SPACE           },
    { InputID::KeyESC,          GLFW_KEY_ESCAPE          },
    { InputID::MouseLEFT,       GLFW_MOUSE_BUTTON_LEFT   },
    { InputID::MouseRIGHT,      GLFW_MOUSE_BUTTON_RIGHT  },
    { InputID::MouseMIDDLE,     GLFW_MOUSE_BUTTON_MIDDLE }
};
