#include "theatre_manager.hpp"
#include "filesystem/filesystem.hpp"
#include "physics_manager.hpp"
#include "theatre/parser/theatre_data.hpp"
#include "theatre/parser/theatre_parser.hpp"
// #include "events/demo_controller.hpp"
#include "things/thing.hpp"
#include "things/actors/nostalgia_player.hpp"
#include "things/actors/light.hpp"
#include "things/devices/collider.hpp"
#include "filesystem/file_data.hpp"
// #include "embedded/images.hpp"
// #include "embedded/models.hpp"
#include "rendering/render_command.hpp"
#include "core/time.hpp"
#include "common/colors.hpp"

#include <vector>
#include <ranges>
#include <glm/glm.hpp>

using namespace ManagerEnums;

static TheatreManager sTheatreManager;
TheatreManager* g_pTheatreManager = &sTheatreManager;

static std::shared_ptr<NostalgiaPlayer> sLocalPlayer{std::make_shared<NostalgiaPlayer>()};
static std::vector<RenderCommand> sRenderCommandQueue{};
static bool sReadyToRender{false};
static TheatreData sCurrentTheatreData{};

bool TheatreManager::Init()
{ PRINT_PRETTY_FUNCTION; return g_pThingFactory->Init(); }

void TheatreManager::Update()
{
    sLocalPlayer->Update();
    for(auto& [id, thing] : mThings)
        { thing->Update(); }
}

void TheatreManager::Tick()
{
    sLocalPlayer->Tick();
    for(auto& [id, thing] : mThings)
        { thing->Tick(); }
}

void TheatreManager::DrawTheatre()
{
    if(IManager::GetTheatreState() != IN_LEVEL)
        { return; }
    light_t::ClearCounts();
    for(auto& [id, thing] : mThings)
    {
        if(!sReadyToRender)
            { return; }
        ID shader{Shaders::BlinnPhong};
        if(auto actor = dynamic_pointer_cast<Actor>(thing))
        {
            if(auto light = dynamic_pointer_cast<light_t>(thing); light && light->IncrementIndex())
            {
                // g_pBackendManager->Graphics()->SetLight(light.get(), shader);
                shader = Shaders::Fullbright;
            }
            if(!actor->mVisible)
                { continue; }
            // g_pBackendManager->Graphics()->BufferRenderCommand({actor, shader});
        }
    }

}

ManagerEnums::TheatreReturnValue_t TheatreManager::TheatreInit(bool is_first_call)
{
    if(!is_first_call)
        { return FINISHED; }

    // g_pDemoController->NotifyOfTheatreChange();

    sReadyToRender = false;

    CreateThings();
    ReadyThings();
    // g_pBackendManager->Graphics()->CreateRenderingData();

    sReadyToRender = true;

    return FINISHED;
}

ManagerEnums::TheatreReturnValue_t TheatreManager::TheatreShutdown(bool is_first_call)
{
    if(!is_first_call)
        { return FINISHED; }

    // g_pDemoController->StopRecording();
    // g_pDemoController->Save();
    sReadyToRender = false;
    DestroyThings();
    // g_pBackendManager->Graphics()->DestroyRenderingData();

    return FINISHED;
}

void TheatreManager::ReadyThings()
{
    for(const auto& [id, thing] : mThings)
        { thing->Ready(); }
}

bool TheatreManager::ThingExists(const ID& uid)
{ return mThings.contains(uid); }

ID TheatreManager::GetType(const ID& uid)
{ return (ThingExists(uid)) ? GetThing(uid)->type() : static_cast<ID>(ID::Invalid); }

void TheatreManager::LoadTheatreData(const TheatreData& data)
{
    sCurrentTheatreData = data;
    IManager::StartNewTheatre();
}

bool TheatreManager::LoadTheatreFromMemory(const std::string& data)
{
    if(!TheatreParser::ParseTheatreFileFromMemory(data, sCurrentTheatreData))
    {
        debug_print("{}Theatre File Data:{}\n{}", Sty::Bold + Fg::Cyan, Sty::Reset, data);
        return print_error("unable to load Theatre");
    }
    IManager::StartNewTheatre();
    return true;
}

bool TheatreManager::LoadTheatreFromFile(const std::string& path)
{
    print_debugv(VERBOSE2, "current working directory: {}", FileSystem::GetCurrentDirectory());
    if(!TheatreParser::ParseTheatreFile(path, sCurrentTheatreData))
        { return print_error("unable to load Theatre file '{}'", path); }
    IManager::StartNewTheatre();
    return true;
}

const TheatreData& TheatreManager::GetInitialState()
{ return sCurrentTheatreData; }

TheatreData TheatreManager::GetCurrentState()
{
    TheatreData data{sCurrentTheatreData};
    data.clear();
    for(const auto& [id, thing] : mThings)
        { data.AddData(thing->GetVariables()); }
    return data;
}

std::vector<ID> TheatreManager::GetThingIDs()
{
    auto keys = std::views::keys(mThings);
    return {keys.begin(), keys.end()};
}

const ID& TheatreManager::CreateThing(const ThingData& cData)
{
    std::shared_ptr<Thing> thing;
    ThingData data = cData;

    if(mThings.contains(data.uid))
    {
        print_warning("A Thing with {} already exists; a new ID will be generated and a duplicate Thing will be made", data.uid);
        if(!UniqueID::Contains(data.uid))
            { std::println("{}[NOTE] {} wasn't generated by `UniqueIDs`, which is what caused the previous warning (it has just been added to avoid future issues){}", Sty::Bold + Fg::Cyan, data.uid, Sty::Reset); }
        data.uid = UniqueID::Generate();
    }

    if(data.type() == ThingType::NostalgiaPlayer)
    {
        thing = static_pointer_cast<Thing>(sLocalPlayer);
        thing->SetVariables(ThingData::PlayerDefaults);
    }
    else
        { thing = mThings[data.uid] = g_pThingFactory->MakeThing(data.type())(); }

    thing->SetVariables(data);
    if(auto collider = dynamic_pointer_cast<Collider>(thing))
        { g_pPhysicsManager->CreateBody(thing->uid(), collider); }
    return thing->uid();
}

std::shared_ptr<NostalgiaPlayer> TheatreManager::GetLocalPlayer()
{ return sLocalPlayer; }

bool TheatreManager::DestroyThing(const ID& id)
{
    if(!mThings.contains(id))
    {
        print_warning("No Thing with {} exists", id);
        return false;
    }
    else if(id == sLocalPlayer->uid())
    {
        print_warning("Cannot destroy the NostalgiaPlayer Thing! ({})", sLocalPlayer->uid());
        print_debug("Player ID: {}, Thing ID: {}", sLocalPlayer->uid(), id);
        return false;
    }
    if(!UniqueID::Contains(id))
        { print_warning("{} is not in 's_ExistingIDs', but is somehow in 'mThings'! The Thing will still be destroyed, but this is highly unusual behaviour!", id); }
    return (mThings.erase(id) != 0);
}

void TheatreManager::CreateThings()
{
    Time::Wait(mDestroyingThings);
    mCreatingThings = true;
    sReadyToRender = false;

    // Clear rendering data and buffer important embedded Resources
    // g_pBackendManager->Graphics()->DestroyRenderingData();
    // g_pBackendManager->Graphics()->BufferTexture({Images::Missing, std::size(Images::Missing), FileType::image_JPG}, UniqueIDs::Reserved::i_Missing);
    // g_pBackendManager->Graphics()->BufferTexture({Images::LightDebug, std::size(Images::LightDebug), FileType::image_JPG}, UniqueIDs::Reserved::i_LightDebug);
    // g_pBackendManager->Graphics()->BufferTexture({Images::COMP04_5, std::size(Images::COMP04_5), FileType::image_PNG}, UniqueIDs::Reserved::i_COMP04_5);
    // g_pBackendManager->Graphics()->BufferTexture({Images::LolBit, std::size(Images::LolBit), FileType::image_PNG}, UniqueIDs::Reserved::i_LolBit);
    // g_pBackendManager->Graphics()->BufferMesh({Models::Error, std::size(Models::Error), FileType::model_OBJ}, UniqueIDs::Reserved::m_Error);
    // g_pBackendManager->Graphics()->BufferMesh({Models::Cube, std::size(Models::Cube), FileType::model_OBJ}, UniqueIDs::Reserved::m_Cube);
    // g_pBackendManager->Graphics()->BufferMesh({Models::Ramiel, std::size(Models::Ramiel), FileType::model_OBJ}, UniqueIDs::Reserved::m_Ramiel);

    sCurrentTheatreData.SetupUIDsAndPriorities();
    sCurrentTheatreData.debug_PrintData();

    for(ThingData& data : sCurrentTheatreData.things_data)
        { CreateThing(data); }

    sReadyToRender = true;
    mCreatingThings = false;
}

void TheatreManager::DestroyThings()
{
    Time::Wait(mCreatingThings);
    mDestroyingThings = true;
#pragma message("When I implement multiple Theatres, they should be able to clear their own sets of IDs")
    for(const auto& [id, thing] : mThings)
    {
        if(auto collider = dynamic_pointer_cast<Collider>(thing))
            { g_pPhysicsManager->DestroyBody(id, collider); }
    }
    UniqueID::Clear();
    mThings.clear();
    mDestroyingThings = false;
}
