#include "glfw_window.hpp"

#include <GLFW/glfw3.h>

#define CONVERT(KeyID, GLFW_KEY) { KeyID, GLFW_KEY },

constinit frozen::map<GLFWInputID, id_t, Input::KeysCount>
WindowGLFW::s_cGLFWInputLookup
{
    CONVERT(GLFW_KEY_0, Key::Zero)
    CONVERT(GLFW_KEY_1, Key::One)
    CONVERT(GLFW_KEY_2, Key::Two)
    CONVERT(GLFW_KEY_3, Key::Three)
    CONVERT(GLFW_KEY_4, Key::Four)
    CONVERT(GLFW_KEY_5, Key::Five)
    CONVERT(GLFW_KEY_6, Key::Six)
    CONVERT(GLFW_KEY_7, Key::Seven)
    CONVERT(GLFW_KEY_8, Key::Eight)
    CONVERT(GLFW_KEY_9, Key::Nine)
    CONVERT(GLFW_KEY_A, Key::A)
    CONVERT(GLFW_KEY_B, Key::B)
    CONVERT(GLFW_KEY_C, Key::C)
    CONVERT(GLFW_KEY_D, Key::D)
    CONVERT(GLFW_KEY_E, Key::E)
    CONVERT(GLFW_KEY_F, Key::F)
    CONVERT(GLFW_KEY_G, Key::G)
    CONVERT(GLFW_KEY_H, Key::H)
    CONVERT(GLFW_KEY_I, Key::I)
    CONVERT(GLFW_KEY_J, Key::J)
    CONVERT(GLFW_KEY_K, Key::K)
    CONVERT(GLFW_KEY_L, Key::L)
    CONVERT(GLFW_KEY_M, Key::M)
    CONVERT(GLFW_KEY_N, Key::N)
    CONVERT(GLFW_KEY_O, Key::O)
    CONVERT(GLFW_KEY_P, Key::P)
    CONVERT(GLFW_KEY_Q, Key::Q)
    CONVERT(GLFW_KEY_R, Key::R)
    CONVERT(GLFW_KEY_S, Key::S)
    CONVERT(GLFW_KEY_T, Key::T)
    CONVERT(GLFW_KEY_U, Key::U)
    CONVERT(GLFW_KEY_V, Key::V)
    CONVERT(GLFW_KEY_W, Key::W)
    CONVERT(GLFW_KEY_X, Key::X)
    CONVERT(GLFW_KEY_Y, Key::Y)
    CONVERT(GLFW_KEY_Z, Key::Z)
    CONVERT(GLFW_KEY_LEFT_SHIFT, Key::LeftShift)
    CONVERT(GLFW_KEY_RIGHT_SHIFT, Key::RightShift)
    CONVERT(GLFW_KEY_LEFT_CONTROL, Key::LeftControl)
    CONVERT(GLFW_KEY_RIGHT_CONTROL, Key::RightControl)
    CONVERT(GLFW_KEY_LEFT_ALT, Key::LeftAlt)
    CONVERT(GLFW_KEY_RIGHT_ALT, Key::RightAlt)
    CONVERT(GLFW_KEY_LEFT_SUPER, Key::LeftSuper)
    CONVERT(GLFW_KEY_RIGHT_SUPER, Key::RightSuper)
    CONVERT(GLFW_KEY_ENTER, Key::Enter)
    CONVERT(GLFW_KEY_BACKSPACE, Key::Backspace)
    CONVERT(GLFW_KEY_TAB, Key::Tab)
    CONVERT(GLFW_KEY_SPACE, Key::Space)
    CONVERT(GLFW_KEY_ESCAPE, Key::Escape)
    CONVERT(GLFW_MOUSE_BUTTON_LEFT, Key::MouseLeft)
    CONVERT(GLFW_MOUSE_BUTTON_RIGHT, Key::MouseRight)
    CONVERT(GLFW_MOUSE_BUTTON_MIDDLE, Key::MouseMiddle)
};
