// 'frozen' maps for converting various values between different windowing libraries and Nostalgia

#include "windowing/glfw.hpp"
#include "GLFW/glfw3.h"

constexpr frozen::map<ID, unsigned int, BindingIDs::KeyIDsCount + BindingIDs::MouseButtonIDsCount - 1>
GLFW_Backend::m_sInputIdToGlfw =
{
    { BindingIDs::KeyZERO,  GLFW_KEY_0 },
    { BindingIDs::KeyONE,   GLFW_KEY_1 },
    { BindingIDs::KeyTWO,   GLFW_KEY_2 },
    { BindingIDs::KeyTHREE, GLFW_KEY_3 },
    { BindingIDs::KeyFOUR,  GLFW_KEY_4 },
    { BindingIDs::KeyFIVE,  GLFW_KEY_5 },
    { BindingIDs::KeySIX,   GLFW_KEY_6 },
    { BindingIDs::KeySEVEN, GLFW_KEY_7 },
    { BindingIDs::KeyEIGHT, GLFW_KEY_8 },
    { BindingIDs::KeyNINE,  GLFW_KEY_9 },
    { BindingIDs::KeyA, GLFW_KEY_A },
    { BindingIDs::KeyB, GLFW_KEY_B },
    { BindingIDs::KeyC, GLFW_KEY_C },
    { BindingIDs::KeyD, GLFW_KEY_D },
    { BindingIDs::KeyE, GLFW_KEY_E },
    { BindingIDs::KeyF, GLFW_KEY_F },
    { BindingIDs::KeyG, GLFW_KEY_G },
    { BindingIDs::KeyH, GLFW_KEY_H },
    { BindingIDs::KeyI, GLFW_KEY_I },
    { BindingIDs::KeyJ, GLFW_KEY_J },
    { BindingIDs::KeyK, GLFW_KEY_K },
    { BindingIDs::KeyL, GLFW_KEY_L },
    { BindingIDs::KeyM, GLFW_KEY_M },
    { BindingIDs::KeyN, GLFW_KEY_N },
    { BindingIDs::KeyO, GLFW_KEY_O },
    { BindingIDs::KeyP, GLFW_KEY_P },
    { BindingIDs::KeyQ, GLFW_KEY_Q },
    { BindingIDs::KeyR, GLFW_KEY_R },
    { BindingIDs::KeyS, GLFW_KEY_S },
    { BindingIDs::KeyT, GLFW_KEY_T },
    { BindingIDs::KeyU, GLFW_KEY_U },
    { BindingIDs::KeyV, GLFW_KEY_V },
    { BindingIDs::KeyW, GLFW_KEY_W },
    { BindingIDs::KeyX, GLFW_KEY_X },
    { BindingIDs::KeyY, GLFW_KEY_Y },
    { BindingIDs::KeyZ, GLFW_KEY_Z },
    { BindingIDs::KeyLEFTSHIFT,    GLFW_KEY_LEFT_SHIFT      },
    { BindingIDs::KeyRIGHTSHIFT,   GLFW_KEY_RIGHT_SHIFT     },
    { BindingIDs::KeyLEFTCONTROL,  GLFW_KEY_LEFT_CONTROL    },
    { BindingIDs::KeyRIGHTCONTROL, GLFW_KEY_RIGHT_CONTROL   },
    { BindingIDs::KeyLEFTALT,      GLFW_KEY_LEFT_ALT        },
    { BindingIDs::KeyRIGHTALT,     GLFW_KEY_RIGHT_ALT       },
    { BindingIDs::KeyLEFTSUPER,    GLFW_KEY_LEFT_SUPER      },
    { BindingIDs::KeyRIGHTSUPER,   GLFW_KEY_RIGHT_SUPER     },
    { BindingIDs::KeyENTER,        GLFW_KEY_ENTER           },
    { BindingIDs::KeyBACKSPACE,    GLFW_KEY_BACKSPACE       },
    { BindingIDs::KeyTAB,          GLFW_KEY_TAB             },
    { BindingIDs::KeySPACE,        GLFW_KEY_SPACE           },
    { BindingIDs::KeyESC,          GLFW_KEY_ESCAPE          },
    { BindingIDs::MouseLEFT,       GLFW_MOUSE_BUTTON_LEFT   },
    { BindingIDs::MouseRIGHT,      GLFW_MOUSE_BUTTON_RIGHT  },
    { BindingIDs::MouseMIDDLE,     GLFW_MOUSE_BUTTON_MIDDLE }
};
