#include "ids.hpp"

constexpr frozen::map<std::string, ID, BindingIDs::end + 26>
BindingIDs::cBindingNames =
{
    // Keys
    { "LShift",          KeyLEFTSHIFT    },
    { "RShift",          KeyRIGHTSHIFT   },
    { "LCtrl",           KeyLEFTCONTROL  },
    { "RCtrl",           KeyRIGHTCONTROL },
    { "LAlt",            KeyLEFTALT      },
    { "RAlt",            KeyRIGHTALT     },
    { "Fn",              KeyFUNCTION     },
    { "LSuper",          KeyLEFTSUPER    },
    { "RSuper",          KeyRIGHTSUPER   },
    { "Enter",           KeyENTER        },
    { "Backspace",       KeyBACKSPACE    },
    { "Tab",             KeyTAB          },
    { "Space",           KeySPACE        },
    { "Escape",          KeyESC          },
    // Mouse Buttons
    { "LeftMouse",       MouseLEFT       },
    { "RightMouse",      MouseRIGHT      },
    { "MiddleMouse",     MouseMIDDLE     },
    // Mouse Motion
    { "MouseX",          MouseMotionX    },
    { "MouseY",          MouseMotionY    },
    // Numbers
    { "0", KeyZERO  },
    { "1", KeyONE   },
    { "2", KeyTWO   },
    { "3", KeyTHREE },
    { "4", KeyFOUR  },
    { "5", KeyFIVE  },
    { "6", KeySIX   },
    { "7", KeySEVEN },
    { "8", KeyEIGHT },
    { "9", KeyNINE  },
    // Letters
    { "A", KeyA },
    { "a", KeyA },
    { "B", KeyB },
    { "b", KeyB },
    { "C", KeyC },
    { "c", KeyC },
    { "D", KeyD },
    { "d", KeyD },
    { "E", KeyE },
    { "e", KeyE },
    { "F", KeyF },
    { "f", KeyF },
    { "G", KeyG },
    { "g", KeyG },
    { "H", KeyH },
    { "h", KeyH },
    { "I", KeyI },
    { "i", KeyI },
    { "J", KeyJ },
    { "j", KeyJ },
    { "K", KeyK },
    { "k", KeyK },
    { "L", KeyL },
    { "l", KeyL },
    { "M", KeyM },
    { "m", KeyM },
    { "N", KeyN },
    { "n", KeyN },
    { "O", KeyO },
    { "o", KeyO },
    { "P", KeyP },
    { "p", KeyP },
    { "Q", KeyQ },
    { "q", KeyQ },
    { "R", KeyR },
    { "r", KeyR },
    { "S", KeyS },
    { "s", KeyS },
    { "T", KeyT },
    { "t", KeyT },
    { "U", KeyU },
    { "u", KeyU },
    { "V", KeyV },
    { "v", KeyV },
    { "W", KeyW },
    { "w", KeyW },
    { "X", KeyX },
    { "x", KeyX },
    { "Y", KeyY },
    { "y", KeyY },
    { "Z", KeyZ },
    { "z", KeyZ },
};
